import * as nsMap from "./Map";
import * as nsSet from "./Set";
import * as nsWeakMap from "./WeakMap";
import * as nsWeakSet from "./WeakSet";
import "./Array.from";
import "./Array.prototype.find";
import "./ArrayBuffer.isView";
import "./String.prototype.startsWith";
import "./Object.assign";
import "./Object.fromEntries";
import "./Object.is";
export { nsMap, nsSet, nsWeakMap, nsWeakSet };
